### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by koddsson** [jsis/nodeschool#1]
Reykjavík University has the space and are very keen on hosting these kind of events.

**Comment by koddsson** [comment]
But other suggestions are welcome.

**Comment by axelg12** [comment]
I agree with RU simply because I know we would get it free or cheap I think. 
Háskólabíó could also be an option

**Comment by kristjanmik** [comment]
RU is an excellent place to start out with. It enables to host this event for no budget if we want. The space is also great!

**Comment by thorsteinsson** [comment]
We've got RU on 13th of Feb.
