### ISSUE TITLE
Stickers.

### ISSUE THREAD

**Issue by koddsson** [jsis/nodeschool#2]
Everybody loves stickers.

Given the Icelandic JS community flair for making [custom logos/stickers](https://github.com/jsis/logos) I think it'd be neat to make some of our own for this event.

**Comment by koddsson** [comment]
There are some templates [here](https://github.com/nodeschool/organizers/blob/master/README.md#make-a-logo).

**Comment by kristjanmik** [comment]
We should follow the hexagon spec and have one sticker per special event we do like this, that would be awesome! @MiniGod and @benediktvaldez I summon your Photoshop skills into this issue.

**Comment by koddsson** [comment]
Given that other nodeschool stickers display famous buildings in their town, I suggest we make ours with the image of [Hallgrímskirkja](http://cdn.flaticon.com/png/512/1800.png)

**Comment by koddsson** [comment]
Here's a quick and dirty mockup from the bar, courtesy of me and @axelg12 

<img width="446" alt="screen shot 2015-07-29 at 9 47 29 pm" src="https://cloud.githubusercontent.com/assets/318208/8970858/8a3fbe10-363b-11e5-9350-8e1b132ebfa9.png">

**Comment by koddsson** [comment]
But we'd love for it to be in the same style as the other nodeschool logos.
